---
name: Banner Settings
rest_endpoint: /dna/intent/api/v1/sites/%v/bannerSettings
put_no_id: true
get_no_id: true
data_source_no_id: true
import_no_id: true
delete_no_id: true
get_extra_query_params: "?_inherited=true"
put_create: true
put_delete: true
doc_category: Network Settings
attributes:
  - model_name: siteId
    type: String
    id: true
    reference: true
    description: The site ID
    example: 5e6f7b3a-2b0b-4a7d-8b1c-0d4b1cd5e1b1
    test_value: catalystcenter_area.test.id
  - model_name: type
    data_path: banner
    response_data_path: response.banner.type
    type: String
    enum_values: [Builtin, Custom]
    description: Banner type
    example: "Custom"
  - model_name: message
    data_path: banner
    response_data_path: response.banner.message
    type: String
    description: Custom message that appears when logging into routers, switches, and hubs. Required for custom type
    example: "Banner message"
test_prerequisites: |
  resource "catalystcenter_area" "test" {
    name        = "Area1"
    parent_name = "Global"
  }
  