// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

//template:end imports

//template:begin testAccDataSource
func TestAccDataSourceCcFloor(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.catalystcenter_floor.test", "name", "Floor1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.catalystcenter_floor.test", "width", "30.5"))
	checks = append(checks, resource.TestCheckResourceAttr("data.catalystcenter_floor.test", "length", "50.5"))
	checks = append(checks, resource.TestCheckResourceAttr("data.catalystcenter_floor.test", "height", "3.5"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceCcFloorPrerequisitesConfig + testAccDataSourceCcFloorConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

//template:end testAccDataSource

//template:begin testPrerequisites
const testAccDataSourceCcFloorPrerequisitesConfig = `
resource "catalystcenter_building" "test" {
  name        = "Building1"
  parent_name = "Global"
  country     = "United States"
  address     = "150 W Tasman Dr, San Jose"
  latitude    = 37.338
  longitude   = -121.832
}

`

//template:end testPrerequisites

//template:begin testAccDataSourceConfig
func testAccDataSourceCcFloorConfig() string {
	config := `resource "catalystcenter_floor" "test" {` + "\n"
	config += `	name = "Floor1"` + "\n"
	config += `	parent_name = "${catalystcenter_building.test.parent_name}/${catalystcenter_building.test.name}"` + "\n"
	config += `	rf_model = "Drywall Office Only"` + "\n"
	config += `	width = 30.5` + "\n"
	config += `	length = 50.5` + "\n"
	config += `	height = 3.5` + "\n"
	config += `}` + "\n"

	config += `
		data "catalystcenter_floor" "test" {
			id = catalystcenter_floor.test.id
		}
	`
	return config
}

//template:end testAccDataSourceConfig
