// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-catalystcenter/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type WirelessPreAuthACL struct {
	Id                        types.String                   `tfsdk:"id"`
	AclListName               types.String                   `tfsdk:"acl_list_name"`
	AclName                   types.String                   `tfsdk:"acl_name"`
	Ipv6AclEnabled            types.Bool                     `tfsdk:"ipv6_acl_enabled"`
	IncludeAutoGeneratedRules types.Bool                     `tfsdk:"include_auto_generated_rules"`
	IpAclRules                []WirelessPreAuthACLIpAclRules `tfsdk:"ip_acl_rules"`
	WalledGardenUrls          types.Set                      `tfsdk:"walled_garden_urls"`
}

type WirelessPreAuthACLIpAclRules struct {
	SourceAddress                 types.String `tfsdk:"source_address"`
	SourceSubnetMaskOrPrefix      types.Int64  `tfsdk:"source_subnet_mask_or_prefix"`
	DestinationAddress            types.String `tfsdk:"destination_address"`
	DestinationSubnetMaskOrPrefix types.Int64  `tfsdk:"destination_subnet_mask_or_prefix"`
	SourcePorts                   types.String `tfsdk:"source_ports"`
	DestinationPorts              types.String `tfsdk:"destination_ports"`
	Protocol                      types.String `tfsdk:"protocol"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath
func (data WirelessPreAuthACL) getPath() string {
	return "/dna/intent/api/v1/wirelessSettings/preAuthAcls"
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin getFallbackPath

// End of section. //template:end getFallbackPath

// Section below is generated&owned by "gen/generator.go". //template:begin getPathDelete

// End of section. //template:end getPathDelete

// Section below is generated&owned by "gen/generator.go". //template:begin getPathGet

// End of section. //template:end getPathGet

// Section below is generated&owned by "gen/generator.go". //template:begin getPathPost

// End of section. //template:end getPathPost

// Section below is generated&owned by "gen/generator.go". //template:begin getPathPut

// End of section. //template:end getPathPut

// Section below is generated&owned by "gen/generator.go". //template:begin getPathIdQuery

// End of section. //template:end getPathIdQuery

// Section below is generated&owned by "gen/generator.go". //template:begin toBody
func (data WirelessPreAuthACL) toBody(ctx context.Context, state WirelessPreAuthACL) string {
	body := ""
	put := false
	if state.Id.ValueString() != "" {
		put = true
	}
	_ = put
	if !data.AclListName.IsNull() {
		body, _ = sjson.Set(body, "aclListName", data.AclListName.ValueString())
	}
	if !data.AclName.IsNull() {
		body, _ = sjson.Set(body, "aclName", data.AclName.ValueString())
	}
	if !data.Ipv6AclEnabled.IsNull() {
		body, _ = sjson.Set(body, "ipv6AclEnabled", data.Ipv6AclEnabled.ValueBool())
	}
	if !data.IncludeAutoGeneratedRules.IsNull() {
		body, _ = sjson.Set(body, "includeAutoGeneratedRules", data.IncludeAutoGeneratedRules.ValueBool())
	}
	if len(data.IpAclRules) > 0 {
		body, _ = sjson.Set(body, "ipAclRules", []interface{}{})
		for _, item := range data.IpAclRules {
			itemBody := ""
			if !item.SourceAddress.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "sourceAddress", item.SourceAddress.ValueString())
			}
			if !item.SourceSubnetMaskOrPrefix.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "sourceSubnetMaskOrPrefix", item.SourceSubnetMaskOrPrefix.ValueInt64())
			}
			if !item.DestinationAddress.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "destinationAddress", item.DestinationAddress.ValueString())
			}
			if !item.DestinationSubnetMaskOrPrefix.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "destinationSubnetMaskOrPrefix", item.DestinationSubnetMaskOrPrefix.ValueInt64())
			}
			if !item.SourcePorts.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "sourcePorts", item.SourcePorts.ValueString())
			}
			if !item.DestinationPorts.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "destinationPorts", item.DestinationPorts.ValueString())
			}
			if !item.Protocol.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "protocol", item.Protocol.ValueString())
			}
			body, _ = sjson.SetRaw(body, "ipAclRules.-1", itemBody)
		}
	}
	if !data.WalledGardenUrls.IsNull() {
		var values []string
		data.WalledGardenUrls.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, "walledGardenUrls", values)
	}
	return body
}

// End of section. //template:end toBody

// Section below is generated&owned by "gen/generator.go". //template:begin fromBody
func (data *WirelessPreAuthACL) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("aclListName"); value.Exists() {
		data.AclListName = types.StringValue(value.String())
	} else {
		data.AclListName = types.StringNull()
	}
	if value := res.Get("aclName"); value.Exists() {
		data.AclName = types.StringValue(value.String())
	} else {
		data.AclName = types.StringNull()
	}
	if value := res.Get("ipv6AclEnabled"); value.Exists() {
		data.Ipv6AclEnabled = types.BoolValue(value.Bool())
	} else {
		data.Ipv6AclEnabled = types.BoolValue(false)
	}
	if value := res.Get("includeAutoGeneratedRules"); value.Exists() {
		data.IncludeAutoGeneratedRules = types.BoolValue(value.Bool())
	} else {
		data.IncludeAutoGeneratedRules = types.BoolValue(true)
	}
	if value := res.Get("ipAclRules"); value.Exists() && len(value.Array()) > 0 {
		data.IpAclRules = make([]WirelessPreAuthACLIpAclRules, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := WirelessPreAuthACLIpAclRules{}
			if cValue := v.Get("sourceAddress"); cValue.Exists() {
				item.SourceAddress = types.StringValue(cValue.String())
			} else {
				item.SourceAddress = types.StringNull()
			}
			if cValue := v.Get("sourceSubnetMaskOrPrefix"); cValue.Exists() {
				item.SourceSubnetMaskOrPrefix = types.Int64Value(cValue.Int())
			} else {
				item.SourceSubnetMaskOrPrefix = types.Int64Null()
			}
			if cValue := v.Get("destinationAddress"); cValue.Exists() {
				item.DestinationAddress = types.StringValue(cValue.String())
			} else {
				item.DestinationAddress = types.StringNull()
			}
			if cValue := v.Get("destinationSubnetMaskOrPrefix"); cValue.Exists() {
				item.DestinationSubnetMaskOrPrefix = types.Int64Value(cValue.Int())
			} else {
				item.DestinationSubnetMaskOrPrefix = types.Int64Null()
			}
			if cValue := v.Get("sourcePorts"); cValue.Exists() {
				item.SourcePorts = types.StringValue(cValue.String())
			} else {
				item.SourcePorts = types.StringValue("0-65535")
			}
			if cValue := v.Get("destinationPorts"); cValue.Exists() {
				item.DestinationPorts = types.StringValue(cValue.String())
			} else {
				item.DestinationPorts = types.StringValue("0-65535")
			}
			if cValue := v.Get("protocol"); cValue.Exists() {
				item.Protocol = types.StringValue(cValue.String())
			} else {
				item.Protocol = types.StringNull()
			}
			data.IpAclRules = append(data.IpAclRules, item)
			return true
		})
	}
	if value := res.Get("walledGardenUrls"); value.Exists() && len(value.Array()) > 0 {
		data.WalledGardenUrls = helpers.GetStringSet(value.Array())
	} else {
		data.WalledGardenUrls = types.SetNull(types.StringType)
	}
}

// End of section. //template:end fromBody

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBody
func (data *WirelessPreAuthACL) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("aclListName"); value.Exists() && !data.AclListName.IsNull() {
		data.AclListName = types.StringValue(value.String())
	} else {
		data.AclListName = types.StringNull()
	}
	if value := res.Get("aclName"); value.Exists() && !data.AclName.IsNull() {
		data.AclName = types.StringValue(value.String())
	} else {
		data.AclName = types.StringNull()
	}
	if value := res.Get("ipv6AclEnabled"); value.Exists() && !data.Ipv6AclEnabled.IsNull() {
		data.Ipv6AclEnabled = types.BoolValue(value.Bool())
	} else if data.Ipv6AclEnabled.ValueBool() != false {
		data.Ipv6AclEnabled = types.BoolNull()
	}
	if value := res.Get("includeAutoGeneratedRules"); value.Exists() && !data.IncludeAutoGeneratedRules.IsNull() {
		data.IncludeAutoGeneratedRules = types.BoolValue(value.Bool())
	} else if data.IncludeAutoGeneratedRules.ValueBool() != true {
		data.IncludeAutoGeneratedRules = types.BoolNull()
	}
	for i := range data.IpAclRules {
		keys := [...]string{"sourceAddress", "sourceSubnetMaskOrPrefix", "destinationAddress", "destinationSubnetMaskOrPrefix", "sourcePorts", "destinationPorts", "protocol"}
		keyValues := [...]string{data.IpAclRules[i].SourceAddress.ValueString(), strconv.FormatInt(data.IpAclRules[i].SourceSubnetMaskOrPrefix.ValueInt64(), 10), data.IpAclRules[i].DestinationAddress.ValueString(), strconv.FormatInt(data.IpAclRules[i].DestinationSubnetMaskOrPrefix.ValueInt64(), 10), data.IpAclRules[i].SourcePorts.ValueString(), data.IpAclRules[i].DestinationPorts.ValueString(), data.IpAclRules[i].Protocol.ValueString()}

		var r gjson.Result
		res.Get("ipAclRules").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get("sourceAddress"); value.Exists() && !data.IpAclRules[i].SourceAddress.IsNull() {
			data.IpAclRules[i].SourceAddress = types.StringValue(value.String())
		} else {
			data.IpAclRules[i].SourceAddress = types.StringNull()
		}
		if value := r.Get("sourceSubnetMaskOrPrefix"); value.Exists() && !data.IpAclRules[i].SourceSubnetMaskOrPrefix.IsNull() {
			data.IpAclRules[i].SourceSubnetMaskOrPrefix = types.Int64Value(value.Int())
		} else {
			data.IpAclRules[i].SourceSubnetMaskOrPrefix = types.Int64Null()
		}
		if value := r.Get("destinationAddress"); value.Exists() && !data.IpAclRules[i].DestinationAddress.IsNull() {
			data.IpAclRules[i].DestinationAddress = types.StringValue(value.String())
		} else {
			data.IpAclRules[i].DestinationAddress = types.StringNull()
		}
		if value := r.Get("destinationSubnetMaskOrPrefix"); value.Exists() && !data.IpAclRules[i].DestinationSubnetMaskOrPrefix.IsNull() {
			data.IpAclRules[i].DestinationSubnetMaskOrPrefix = types.Int64Value(value.Int())
		} else {
			data.IpAclRules[i].DestinationSubnetMaskOrPrefix = types.Int64Null()
		}
		if value := r.Get("sourcePorts"); value.Exists() && !data.IpAclRules[i].SourcePorts.IsNull() {
			data.IpAclRules[i].SourcePorts = types.StringValue(value.String())
		} else if data.IpAclRules[i].SourcePorts.ValueString() != "0-65535" {
			data.IpAclRules[i].SourcePorts = types.StringNull()
		}
		if value := r.Get("destinationPorts"); value.Exists() && !data.IpAclRules[i].DestinationPorts.IsNull() {
			data.IpAclRules[i].DestinationPorts = types.StringValue(value.String())
		} else if data.IpAclRules[i].DestinationPorts.ValueString() != "0-65535" {
			data.IpAclRules[i].DestinationPorts = types.StringNull()
		}
		if value := r.Get("protocol"); value.Exists() && !data.IpAclRules[i].Protocol.IsNull() {
			data.IpAclRules[i].Protocol = types.StringValue(value.String())
		} else {
			data.IpAclRules[i].Protocol = types.StringNull()
		}
	}
	if value := res.Get("walledGardenUrls"); value.Exists() && !data.WalledGardenUrls.IsNull() {
		data.WalledGardenUrls = helpers.GetStringSet(value.Array())
	} else {
		data.WalledGardenUrls = types.SetNull(types.StringType)
	}
}

// End of section. //template:end updateFromBody

// Section below is generated&owned by "gen/generator.go". //template:begin isNull
func (data *WirelessPreAuthACL) isNull(ctx context.Context, res gjson.Result) bool {
	if !data.AclListName.IsNull() {
		return false
	}
	if !data.AclName.IsNull() {
		return false
	}
	if !data.Ipv6AclEnabled.IsNull() {
		return false
	}
	if !data.IncludeAutoGeneratedRules.IsNull() {
		return false
	}
	if len(data.IpAclRules) > 0 {
		return false
	}
	if !data.WalledGardenUrls.IsNull() {
		return false
	}
	return true
}

// End of section. //template:end isNull
