// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
)

//template:end imports

//template:begin types
type AssociateSiteToNetworkProfile struct {
	Id               types.String `tfsdk:"id"`
	NetworkProfileId types.String `tfsdk:"network_profile_id"`
	SiteId           types.String `tfsdk:"site_id"`
}

//template:end types

//template:begin getPath
func (data AssociateSiteToNetworkProfile) getPath() string {
	return fmt.Sprintf("/dna/intent/api/v1/networkprofile/%v/site/%v", data.NetworkProfileId.ValueString(), data.SiteId.ValueString())
}

//template:end getPath

//template:begin getPathDelete

//template:end getPathDelete

//template:begin toBody
func (data AssociateSiteToNetworkProfile) toBody(ctx context.Context, state AssociateSiteToNetworkProfile) string {
	body := ""
	return body
}

//template:end toBody

//template:begin fromBody
func (data *AssociateSiteToNetworkProfile) fromBody(ctx context.Context, res gjson.Result) {
}

//template:end fromBody

//template:begin updateFromBody
func (data *AssociateSiteToNetworkProfile) updateFromBody(ctx context.Context, res gjson.Result) {
}

//template:end updateFromBody

//template:begin isNull
func (data *AssociateSiteToNetworkProfile) isNull(ctx context.Context, res gjson.Result) bool {
	if !data.NetworkProfileId.IsNull() {
		return false
	}
	if !data.SiteId.IsNull() {
		return false
	}
	return true
}

//template:end isNull
