// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type Area struct {
	Id         types.String `tfsdk:"id"`
	Name       types.String `tfsdk:"name"`
	ParentName types.String `tfsdk:"parent_name"`
}

//template:end types

//template:begin getPath
func (data Area) getPath() string {
	return "/dna/intent/api/v1/site"
}

//template:end getPath

//template:begin toBody
func (data Area) toBody(ctx context.Context, state Area) string {
	body := ""
	body, _ = sjson.Set(body, "type", "area")
	if !data.Name.IsNull() {
		body, _ = sjson.Set(body, "site.area.name", data.Name.ValueString())
	}
	if !data.ParentName.IsNull() {
		body, _ = sjson.Set(body, "site.area.parentName", data.ParentName.ValueString())
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *Area) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("response.0.name"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *Area) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("response.0.name"); value.Exists() && !data.Name.IsNull() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
}

//template:end updateFromBody
