// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type AssignCredentials struct {
	Id            types.String `tfsdk:"id"`
	SiteId        types.String `tfsdk:"site_id"`
	CliId         types.String `tfsdk:"cli_id"`
	SnmpV2ReadId  types.String `tfsdk:"snmp_v2_read_id"`
	SnmpV2WriteId types.String `tfsdk:"snmp_v2_write_id"`
	SnmpV3Id      types.String `tfsdk:"snmp_v3_id"`
	HttpsRead     types.String `tfsdk:"https_read"`
	HttpsWrite    types.String `tfsdk:"https_write"`
}

//template:end types

//template:begin getPath
func (data AssignCredentials) getPath() string {
	return "/dna/intent/api/v2/credential-to-site"
}

//template:end getPath

//template:begin toBody
func (data AssignCredentials) toBody(ctx context.Context, state AssignCredentials) string {
	body := ""
	if !data.CliId.IsNull() {
		body, _ = sjson.Set(body, "cliId", data.CliId.ValueString())
	}
	if !data.SnmpV2ReadId.IsNull() {
		body, _ = sjson.Set(body, "snmpV2ReadId", data.SnmpV2ReadId.ValueString())
	}
	if !data.SnmpV2WriteId.IsNull() {
		body, _ = sjson.Set(body, "snmpV2WriteId", data.SnmpV2WriteId.ValueString())
	}
	if !data.SnmpV3Id.IsNull() {
		body, _ = sjson.Set(body, "snmpV3Id", data.SnmpV3Id.ValueString())
	}
	if !data.HttpsRead.IsNull() {
		body, _ = sjson.Set(body, "httpRead", data.HttpsRead.ValueString())
	}
	if !data.HttpsWrite.IsNull() {
		body, _ = sjson.Set(body, "httpWrite", data.HttpsWrite.ValueString())
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *AssignCredentials) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("response.#(key=\"credential.cli\").value.0.objReferences.0"); value.Exists() {
		data.CliId = types.StringValue(value.String())
	} else {
		data.CliId = types.StringNull()
	}
	if value := res.Get("response.#(key=\"credential.snmp_v2_read\").value.0.objReferences.0"); value.Exists() {
		data.SnmpV2ReadId = types.StringValue(value.String())
	} else {
		data.SnmpV2ReadId = types.StringNull()
	}
	if value := res.Get("response.#(key=\"credential.snmp_v2_write\").value.0.objReferences.0"); value.Exists() {
		data.SnmpV2WriteId = types.StringValue(value.String())
	} else {
		data.SnmpV2WriteId = types.StringNull()
	}
	if value := res.Get("response.#(key=\"credential.snmp_v3\").value.0.objReferences.0"); value.Exists() {
		data.SnmpV3Id = types.StringValue(value.String())
	} else {
		data.SnmpV3Id = types.StringNull()
	}
	if value := res.Get("response.#(key=\"credential.http.read\").value.0.objReferences.0"); value.Exists() {
		data.HttpsRead = types.StringValue(value.String())
	} else {
		data.HttpsRead = types.StringNull()
	}
	if value := res.Get("response.#(key=\"credential.http.write\").value.0.objReferences.0"); value.Exists() {
		data.HttpsWrite = types.StringValue(value.String())
	} else {
		data.HttpsWrite = types.StringNull()
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *AssignCredentials) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("response.#(key=\"credential.cli\").value.0.objReferences.0"); value.Exists() && !data.CliId.IsNull() {
		data.CliId = types.StringValue(value.String())
	} else {
		data.CliId = types.StringNull()
	}
	if value := res.Get("response.#(key=\"credential.snmp_v2_read\").value.0.objReferences.0"); value.Exists() && !data.SnmpV2ReadId.IsNull() {
		data.SnmpV2ReadId = types.StringValue(value.String())
	} else {
		data.SnmpV2ReadId = types.StringNull()
	}
	if value := res.Get("response.#(key=\"credential.snmp_v2_write\").value.0.objReferences.0"); value.Exists() && !data.SnmpV2WriteId.IsNull() {
		data.SnmpV2WriteId = types.StringValue(value.String())
	} else {
		data.SnmpV2WriteId = types.StringNull()
	}
	if value := res.Get("response.#(key=\"credential.snmp_v3\").value.0.objReferences.0"); value.Exists() && !data.SnmpV3Id.IsNull() {
		data.SnmpV3Id = types.StringValue(value.String())
	} else {
		data.SnmpV3Id = types.StringNull()
	}
	if value := res.Get("response.#(key=\"credential.http.read\").value.0.objReferences.0"); value.Exists() && !data.HttpsRead.IsNull() {
		data.HttpsRead = types.StringValue(value.String())
	} else {
		data.HttpsRead = types.StringNull()
	}
	if value := res.Get("response.#(key=\"credential.http.write\").value.0.objReferences.0"); value.Exists() && !data.HttpsWrite.IsNull() {
		data.HttpsWrite = types.StringValue(value.String())
	} else {
		data.HttpsWrite = types.StringNull()
	}
}

//template:end updateFromBody
