// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type TemplateVersion struct {
	Id         types.String `tfsdk:"id"`
	TemplateId types.String `tfsdk:"template_id"`
	Comments   types.String `tfsdk:"comments"`
}

//template:end types

//template:begin getPath
func (data TemplateVersion) getPath() string {
	return "/dna/intent/api/v1/template-programmer/template/version"
}

//template:end getPath

//template:begin getPathDelete

//template:end getPathDelete

//template:begin toBody
func (data TemplateVersion) toBody(ctx context.Context, state TemplateVersion) string {
	body := ""
	if !data.TemplateId.IsNull() {
		body, _ = sjson.Set(body, "templateId", data.TemplateId.ValueString())
	}
	if !data.Comments.IsNull() {
		body, _ = sjson.Set(body, "comments", data.Comments.ValueString())
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *TemplateVersion) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("0.templateId"); value.Exists() {
		data.TemplateId = types.StringValue(value.String())
	} else {
		data.TemplateId = types.StringNull()
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *TemplateVersion) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("0.templateId"); value.Exists() && !data.TemplateId.IsNull() {
		data.TemplateId = types.StringValue(value.String())
	} else {
		data.TemplateId = types.StringNull()
	}
}

//template:end updateFromBody

//template:begin isNull
func (data *TemplateVersion) isNull(ctx context.Context, res gjson.Result) bool {
	if !data.TemplateId.IsNull() {
		return false
	}
	if !data.Comments.IsNull() {
		return false
	}
	return true
}

//template:end isNull
