// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

//template:end imports

//template:begin testAcc
func TestAccCcBuilding(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("catalystcenter_building.test", "name", "Building1"))
	checks = append(checks, resource.TestCheckResourceAttr("catalystcenter_building.test", "country", "United States"))
	checks = append(checks, resource.TestCheckResourceAttr("catalystcenter_building.test", "address", "150 W Tasman Dr, San Jose"))
	checks = append(checks, resource.TestCheckResourceAttr("catalystcenter_building.test", "latitude", "37.338"))
	checks = append(checks, resource.TestCheckResourceAttr("catalystcenter_building.test", "longitude", "-121.832"))

	var steps []resource.TestStep
	if os.Getenv("SKIP_MINIMUM_TEST") == "" {
		steps = append(steps, resource.TestStep{
			Config: testAccCcBuildingConfig_minimum(),
		})
	}
	steps = append(steps, resource.TestStep{
		Config: testAccCcBuildingConfig_all(),
		Check:  resource.ComposeTestCheckFunc(checks...),
	})
	steps = append(steps, resource.TestStep{
		ResourceName: "catalystcenter_building.test",
		ImportState:  true,
	})

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps:                    steps,
	})
}

//template:end testAcc

//template:begin testPrerequisites
//template:end testPrerequisites

//template:begin testAccConfigMinimal
func testAccCcBuildingConfig_minimum() string {
	config := `resource "catalystcenter_building" "test" {` + "\n"
	config += `	name = "Building1"` + "\n"
	config += `	parent_name = "Global"` + "\n"
	config += `	country = "United States"` + "\n"
	config += `	address = "150 W Tasman Dr, San Jose"` + "\n"
	config += `}` + "\n"
	return config
}

//template:end testAccConfigMinimal

//template:begin testAccConfigAll
func testAccCcBuildingConfig_all() string {
	config := `resource "catalystcenter_building" "test" {` + "\n"
	config += `	name = "Building1"` + "\n"
	config += `	parent_name = "Global"` + "\n"
	config += `	country = "United States"` + "\n"
	config += `	address = "150 W Tasman Dr, San Jose"` + "\n"
	config += `	latitude = 37.338` + "\n"
	config += `	longitude = -121.832` + "\n"
	config += `}` + "\n"
	return config
}

//template:end testAccConfigAll
